apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: planes.example.com
spec:
  group: example.com
  names:
    kind: Plane
    listKind: PlaneList
    plural: planes
    singular: plane
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                webImage:
                  type: string
                spaceImage:
                  type: string
                liveImage:
                  type: string
                apiImage:
                  type: string
                workerImage:
                  type: string
                beatWorkerImage:
                  type: string
                replicas:
                  type: object
                  properties:
                    web:
                      type: integer
                    space:
                      type: integer
                    live:
                      type: integer
                    api:
                      type: integer
                    worker:
                      type: integer
                    beatWorker:
                      type: integer
                resources:
                  type: object
                  additionalProperties:
                    type: string
                config:
                  type: object
                  additionalProperties:
                    type: string
