apiVersion: example.com/v1
kind: Plane
metadata:
  name: example-plane
  namespace: default
spec:
  webImage: plane-ce-web:latest
  spaceImage: plane-ce-space:latest
  liveImage: plane-ce-live:latest
  apiImage: plane-ce-api:latest
  workerImage: plane-ce-worker:latest
  beatWorkerImage: plane-ce-beat-worker:latest
  replicas:
    web: 2
    space: 1
    live: 1
    api: 2
    worker: 2
    beatWorker: 1
  resources:
    memory: "512Mi"
    cpu: "250m"
  config:
    DATABASE_URL: "postgresql://user:password@db.example.com:5432/plane"
    REDIS_URL: "redis://redis.example.com:6379"
