apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: planece.plane.co
  annotations:
    # Additional metadata for documentation and versioning
    plane.co/description: "Custom Resource Definition for Plane Community Edition"
    plane.co/version: "1.0.0"
spec:
  group: plane.co
  names:
    kind: PlaneCE
    listKind: PlaneCEList
    plural: planece
    singular: planece
    shortNames:
      - plane
      - planes
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
                  description: Number of Plane CE replicas
                image:
                  type: string
                  description: Plane CE container image
                resources:
                  type: object
                  description: Resource requests and limits
                  properties:
                    requests:
                      type: object
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                    limits:
                      type: object
                      properties:
                        cpu:
                          type: string
                        memory:
                          type: string
                config:
                  type: object
                  additionalProperties: true
                  description: Plane CE application-specific configuration
